packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  typescript: ^5.6.3
  tailwindcss: ^3.4.14
  zod: ^3.23.8
  drizzle-orm: ^0.36.4

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
