/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FirstLaunchImport } from './routes/first-launch'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FirstLaunchRoute = FirstLaunchImport.update({
  id: '/first-launch',
  path: '/first-launch',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/first-launch': {
      id: '/first-launch'
      path: '/first-launch'
      fullPath: '/first-launch'
      preLoaderRoute: typeof FirstLaunchImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/first-launch': typeof FirstLaunchRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/first-launch': typeof FirstLaunchRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/first-launch': typeof FirstLaunchRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/first-launch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/first-launch'
  id: '__root__' | '/' | '/first-launch'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirstLaunchRoute: typeof FirstLaunchRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirstLaunchRoute: FirstLaunchRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/first-launch"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/first-launch": {
      "filePath": "first-launch.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
